version: '3'
services:
  db:
    container_name: postgres_db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./app.env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  db:
    driver: local